### ISSUE TITLE
Network connection or i dont know

### ISSUE THREAD

**Issue by dolle123** [Sh1Yo/x8#47]
hello am getting this issues when i run this tool against a target, please can you help ...???

thread 'main' panicked at src/network/request.rs:323:58:
called `Result::unwrap()` on an `Err` value: http::Error(InvalidUri(TooLong))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Sh1Yo** [comment]
i think it says that uri is too long and if you decrease the uri length it should work fine

**Comment by dolle123** [comment]
am using a wordlist ... 
x8 -u "target/login" -X GET -w path/to/wordlist

i used -X POST and it seemed to be working fine.

i would like to suggest this 
add this instruction to the installation

after installing using cargo or by cloning the repo,

cp the x8 binary into /usr/local/bin to be to use it directly from anywhere on the terminal

**Comment by Sh1Yo** [comment]
looks like a good issue then
 i think the problem is that you have a wordlist with very long parameters and it causes this error. This shoudn't happen though

I will look into it when i will feel better. For now you can manually specify `-m` argument like this `-m 64` to manually limit the amount of parameters to send per request. You can also try to shuffle your wordlist so that big words will be mixed with smaller ones

copying the binary to /usr/local/bin looks like a good suggestion as well. Looks like some people have encountered problems with this

**Comment by w2xim3** [comment]
@Sh1Yo - Any kind of try catch to handle this ?


cat katanaurl | urldedupe | grep aspx | x8 -X GET POST -u /dev/stdin -o parameters


2 hours laters: 


thread 'main' panicked at /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/x8-4.3.2/src/network/request.rs:341:32:
called `Result::unwrap()` on an `Err` value: ToStrError { _priv: () }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
